aws-region        = "eu-central-1"
aws-profile       = "default"
user-data-script  = "./scripts/spinup.sh"
instance-ami      = "ami-0a261c0e5f51090b1"
instance-key-name = "mbition"
instance-tag-name = "mbition-instance"
iam-role-name     = "mbition"